packages:
  - 'apps/*'
  - 'packages/*'
packages:
  - 'apps/*'
  - 'packages/*'
packages:
  - 'apps/*'
  - 'packages/*'
packages:
  - 'apps/*'
  - 'packages/*'
packages:
  - 'apps/*'
  - 'packages/*'
  - 'components'
packages:
  - 'apps/*'
  - 'packages/*'
packages:
  - 'apps/**'
  - 'packages/**'
packages:
  - 'apps/*'
  - 'packages/*'
  - 'components'
packages:
  - 'apps/**'
  - 'packages/**'